Document: sbbs
Title: Debian sbbs Manual
Author: <insert document author here>
Abstract: This manual describes what sbbs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sbbs/sbbs.sgml.gz

Format: postscript
Files: /usr/share/doc/sbbs/sbbs.ps.gz

Format: text
Files: /usr/share/doc/sbbs/sbbs.text.gz

Format: HTML
Index: /usr/share/doc/sbbs/html/index.html
Files: /usr/share/doc/sbbs/html/*.html

  
