.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH synchronet 1 "December 11, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
synchronet \-
Synchronet BBS Software
.SH DESCRIPTION
This manual page documents briefly the
.B Synchronet
Bulletin Board System (SBBS) Software, which is a free software package            
that can turn your personal computer into your own custom online service               
supporting multiple simultaneous users with hierarchical message and file              
areas, multi-user chat, and the ever-popular BBS door games.  
.PP
Synchronet development began in 1990 as a program for single-tasking MS-DOS            
compatible computers and Hayes compatible modems.  In November of 1999, the            
author began further development of Synchronet specifically for the Internet           
community and it has since been substantially redesigned as an Internet
capable BBS package for Win32 and Unix-x86 platforms integrating standard
Internet protocols such as Telnet, SSH, FTP, SMTP, POP3, IRC, NNTP, and HTTP.
.SH Programs
These are the programs associated with Synchonet:

.TP
.B sbbs
 \- main executable

.TP
.B scfg
 \- main Synchronet configuration utility.

.TP
.B sbbsecho
 \- main Synchronet configuration utility.

.TP
.B ueditor
 \- User Editor.

.TP
.B umonitor
 \- User monitor.

.TP
.B unbaja
 \- Synchronet unbaja.

.TP
.B addfiles
 \- Adds Files to Synchronet File Database.

.TP
.B allusers
 \- Synchronet allusers utility.

.TP
.B ans2asc
 \- ANSI to Synchronet Ctrl-A message format conversion utility.

.TP
.B asc2ans
 \- Converts Synchronet Ctrl-A file to ANSI escape sequences.

.TP
.B baja
 \- Synchronet Baja compiler.

.TP
.B chksmb
 \- Checks Synchronet mail/message base for validity

.TP
.B delfiles
 \- Removes Files from Synchronet File Database.

.TP
.B dupefind
 \- Synchronet Duplicate File Finder

.TP
.B echocfg
 \- Synchronet echocfg utility.

.TP
.B filelist
 \- Generate Synchronet File Directory Listings

.TP
.B fixsmb
 \- Rebuild Synchronet Message/Mail Base

.TP
.B jsexec
 \- Synchronet jsexec utility.

.TP
.B makehelp
 \- Synchronet makehelp utility.

.TP
.B makeuser
 \- Synchronet makeuser utility.

.TP
.B node
 \- Synchronet node utility.

.TP
.B qwknodes
 \- Synchronet qwknodes utility.

.TP
.B sbbsmono
 \- Synchronet sbbsmono utility.

.TP
.B sexyz
 \- Synchronet External X/Y/ZMODEM (SEXYZ) File Transfer Protocol Driver

.TP
.B slog
\- Synchronet slog utility

.TP
.B smbactiv
\- Checks Synchronet Message Base Activity.

.TP
.B smbutil
\- Synchronet Synchronet Message Base Utility.


.SH SEE ALSO
 
.BR addfiles (1),
.BR allusers (1),
.BR ans2asc (1),
.BR asc2ans (1),
.BR baja (1),
.BR chksmb (1),
.BR delfiles (1),
.BR dupefind (1),
.BR echocfg (1),
.BR filelist (1),
.BR fixsmb (1),
.BR jsexec (1),
.BR makehelp (1),
.BR makeuser (1),
.BR node (1),
.BR qwknodes (1),
.BR sbbs (1),
.BR sbbsecho (1),
.BR scfg (1),
.BR sbbsmono (1),
.BR sexyz (1),
.BR slog (1),
.BR smbaciv (1),
.BR smbutil (1),
.BR ueditor (1),
.BR umonitor (1),
.BR unbaja (1).
.SH AUTHOR
Synchronet was written by Rob Swindell.
.PP
This manual page was written by Robert James Clay <jame@rocasa.us>,
for the Debian project (but may be used by others).

